version: '3'
services:

  # backend
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: vgs-backend
    ports:
      - 8000:8000
    tty: true # コンテナの起動永続化
    volumes:
      - ./backend:/go/src/github.com/NananoMasuda/wallet-watch-app/backend
      - .git:/go/src/github.com/NananoMasuda/wallet-watch-app/.git
    depends_on:
      - 'db'
  # frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vgs-frontend
    ports:
      - 8080:8080
    tty: true # コンテナの起動永続化
    volumes:
      - ./frontend:/usr/src/app/frontend
      - .git:/usr/src/app/.git
  # DB
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: vgs-db
    ports:
      - 33060:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    volumes:
      - ./db/mysql-store:/var/lib/mysql
      - ./db/mysql-logs:/var/log/mysql